// Generated by https://quicktype.io

export enum Genre {
    Shonen = "Shonen",
    Mystery = "Mystery",
    PsychologicalThriller = "Psychological Thriller",
    Superhero = "Superhero",
    Adventure = "Adventure",
    Fantasy = "Fantasy",
    DarkFantasy = "Dark Fantasy",
    Horror = "Horror",
    Supernatural = "Supernatural",
    Action = "Action"
}

// Generated by https://quicktype.io

export interface BooksBase {
    title: string;
    img: string;
    date: string;
    author: string[];
    description?: string;
    rating?: number;
    link: string;
    link2: string;
    genre: Genre;
    isbn?: Isbn[];
}

export interface Isbn {
    type: Type;
    identifier: string;
}

export enum Type {
    Isbn10 = "ISBN_10",
    Isbn13 = "ISBN_13",
    Other = "OTHER",
}
